apiVersion: v1
kind: Secret
metadata:
  name: dex-tls
  namespace: dex
type: Opaque
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIB/jCCAYWgAwIBAgIIGiIRZdsY1ZswCgYIKoZIzj0EAwMwIDEeMBwGA1UEAxMV
    bWluaWNhIHJvb3QgY2EgNzI5MGI2MB4XDTI1MDIxMzE5MjQzNloXDTI3MDMxNTE4
    MjQzNlowJDEiMCAGA1UEAxMZZGV4LmRleC5zdmMuY2x1c3Rlci5sb2NhbDB2MBAG
    ByqGSM49AgEGBSuBBAAiA2IABOXOUhakYrIsNnmWSrDNk0VAB3HLjlxIvDBKt/As
    7kEFZyi3Q+6kPwDGZlYS/CLBQz7MleB57xV+BTXeU4C9JJ2VYfUzrzUWMI9U2a+/
    XAWc1L2GDw6TrLV2COFJQ7njlqOBhzCBhDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0l
    BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgw
    FoAUmUQQlLj97WtsbH451iI74L8+H6IwJAYDVR0RBB0wG4IZZGV4LmRleC5zdmMu
    Y2x1c3Rlci5sb2NhbDAKBggqhkjOPQQDAwNnADBkAjAr3xJ+MuSx1IsabimAlaIC
    FvzA7VqtukdJ4ycZ5ndZlC3BOAHw8LEotgYHQpBItjQCMF7x/LkdBThU1nCChoA6
    r5F8RrqBNPeHeaItjnPpYq6sT3dDqGQF9Rm7bbaG6ExhKA==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIG2AgEAMBAGByqGSM49AgEGBSuBBAAiBIGeMIGbAgEBBDDMWWagdOx7Neqeeg2g
    ofPS9ipeeliiTUv6B/9+oiTMGlTRMPHu4ruSqS7kiw3oBQuhZANiAATlzlIWpGKy
    LDZ5lkqwzZNFQAdxy45cSLwwSrfwLO5BBWcot0PupD8AxmZWEvwiwUM+zJXgee8V
    fgU13lOAvSSdlWH1M681FjCPVNmvv1wFnNS9hg8Ok6y1dgjhSUO545Y=
    -----END PRIVATE KEY-----
