global:
  baseDomain: jumpstarter.127.0.0.1.nip.io
  metrics:
    enabled: false
jumpstarter-controller:
  grpc:
    mode: "ingress"
  config:
    authentication:
      jwt:
        - issuer:
            url: https://kubernetes.default.svc.cluster.local
            audiences:
              - https://kubernetes.default.svc.cluster.local
            audienceMatchPolicy: MatchAny
            certificateAuthority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
