jumpstarter-controller:
  config:
    authentication:
      jwt:
        - issuer:
            url: https://kubernetes.default.svc.cluster.local
            audiences:
              - https://kubernetes.default.svc.cluster.local
            audienceMatchPolicy: MatchAny
            certificateAuthority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          claimMappings:
            username:
              claim: "sub"
              prefix: "kubernetes:"
