jumpstarter-controller:
  config:
    provisioning:
      enabled: true
    authentication:
      jwt:
      - issuer:
          url: https://dex.dex.svc.cluster.local:5556
          audiences:
          - jumpstarter-cli
          audienceMatchPolicy: MatchAny
          certificateAuthority: placeholder
        claimMappings:
          username:
            claim: "name"
            prefix: "dex:"
