name: selftest
on:
  - push
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: e2e
      - uses: ./e2e
        with:
          controller-ref: main
          jumpstarter-ref: main
