name: selftest
on:
  - push
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-13 # arm-based macOS runners does not support nested virt
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: e2e
      - uses: ./e2e
        with:
          controller-ref: main
          jumpstarter-ref: main
